// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://domqgujyiqreiookmlkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbXFndWp5aXFyZWlvb2ttbGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjU2NzAsImV4cCI6MjA2NjgwMTY3MH0.aASDaUvdiHaO2C3xCr12gu1iIneopZ3VkzoNQc-UgVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});